# Generated by Django 5.1.15 on 2026-10-07 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('documents', '0002_document_error_message_document_processing_metadata_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Nouvelle session pédagogique', max_length=255, verbose_name='Titre de la session')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='courses.course', verbose_name="Cours d'ancrage")),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='documents.document', verbose_name="Document d'ancrage")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='organizations.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session de chat',
                'verbose_name_plural': 'Sessions de chat',
                'db_table': 'chat_session',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant / Tuteur'), ('system', 'Système')], default='user', max_length=20, verbose_name='Rôle')),
                ('content', models.TextField(verbose_name='Contenu du message')),
                ('command', models.CharField(blank=True, help_text='EXPLAIN, SIMPLIFY, SUMMARY, EXAMPLE, QUIZ, REVISION, COMPARE, DEFINE', max_length=50, null=True, verbose_name='Commande pédagogique')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='Sources documentaires citées')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens consommés')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Métadonnées d'inférence")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Message de chat',
                'verbose_name_plural': 'Messages de chat',
                'db_table': 'chat_message',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['organization', 'user', '-updated_at'], name='chat_sessio_organiz_5e506f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='chat_sessio_user_id_6380f6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_messag_session_4940cf_idx'),
        ),
    ]
