# Generated by Django 5.1.15 on 2026-10-05 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'organisation")),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='Logo')),
                ('plan', models.CharField(choices=[('FREE', 'Gratuit'), ('PRO', 'Professionnel'), ('ENTERPRISE', 'Entreprise')], default='FREE', max_length=30, verbose_name="Plan d'abonnement")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'organizations_organization',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Propriétaire'), ('ADMIN', 'Administrateur'), ('TEACHER', 'Enseignant / Formateur'), ('STUDENT', 'Apprenant / Étudiant')], default='STUDENT', max_length=20, verbose_name='Rôle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Membre d'organisation",
                'verbose_name_plural': "Membres d'organisation",
                'db_table': 'organizations_member',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_member')],
            },
        ),
    ]
