# Generated by Django 5.1.15 on 2026-10-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Gratuit'), ('PRO', 'Professionnel'), ('BUSINESS', 'Business'), ('ENTERPRISE', 'Entreprise')], default='FREE', max_length=30, verbose_name="Plan d'abonnement"),
        ),
    ]
