# Generated by Django 5.1.15 on 2026-10-05 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nom du fichier original')),
                ('file_type', models.CharField(max_length=50, verbose_name='Format du fichier (pdf, docx, pptx, txt)')),
                ('file_size', models.PositiveBigIntegerField(help_text='Taille en octets', verbose_name='Taille du fichier')),
                ('storage_key', models.CharField(max_length=512, unique=True, verbose_name='Clé de stockage (chemin S3 / local)')),
                ('language', models.CharField(default='fr', max_length=10, verbose_name='Langue principale du document')),
                ('page_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de pages estimé')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploadé'), ('PROCESSING', 'En cours de traitement'), ('READY', 'Prêt'), ('FAILED', 'Échoué'), ('ARCHIVED', 'Archivé')], db_index=True, default='UPLOADED', max_length=20, verbose_name='Statut du document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'importation")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization', verbose_name='Organisation')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire / Auteur')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents_document',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'status'], name='documents_d_organiz_b8cccc_idx'), models.Index(fields=['organization', '-created_at'], name='documents_d_organiz_6d035c_idx')],
            },
        ),
    ]
