# Generated by Django 5.1.15 on 2026-10-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name="Message d'erreur"),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées du pipeline'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploadé'), ('EXTRACTING', 'Extracting'), ('OCR', 'OCR'), ('STRUCTURING', 'Structuring'), ('CHUNKING', 'Chunking'), ('PROCESSING', 'En cours de traitement'), ('COMPLETED', 'Completed'), ('READY', 'Prêt'), ('FAILED', 'Échoué'), ('ARCHIVED', 'Archivé')], db_index=True, default='UPLOADED', max_length=20, verbose_name='Statut du document'),
        ),
    ]
