# Generated by Django 5.1.15 on 2026-10-06 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('documents', '0002_document_error_message_document_processing_metadata_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du QCM')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('type', models.CharField(choices=[('TRAINING', 'Entraînement'), ('EXAM', 'Examen'), ('REVISION', 'Révision')], db_index=True, default='TRAINING', max_length=20, verbose_name='Mode de quiz')),
                ('difficulty', models.CharField(choices=[('EASY', 'Facile'), ('MEDIUM', 'Moyen'), ('HARD', 'Difficile')], default='MEDIUM', max_length=20, verbose_name='Niveau de difficulté')),
                ('time_limit_minutes', models.PositiveIntegerField(default=15, verbose_name='Temps limite (minutes)')),
                ('passing_score_percentage', models.PositiveIntegerField(default=70, verbose_name='Score de validation (%)')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='PUBLISHED', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='courses.course', verbose_name='Cours associé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='documents.document', verbose_name='Document source')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'QCM / Quiz',
                'verbose_name_plural': 'QCM / Quiz',
                'db_table': 'quizzes_quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0, verbose_name='Score obtenu (%)')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Nombre total de questions')),
                ('correct_answers_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de bonnes réponses')),
                ('passed', models.BooleanField(default=False, verbose_name='Réussi (seuil atteint)')),
                ('answers_data', models.JSONField(blank=True, default=dict, verbose_name='Données des réponses soumises {question_id: answer_id}')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Début de la tentative')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la tentative')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Temps passé (secondes)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='Quiz tenté')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
            ],
            options={
                'verbose_name': 'Tentative de QCM',
                'verbose_name_plural': 'Tentatives de QCM',
                'db_table': 'quizzes_quizattempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Énoncé de la question')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Explication pédagogique de la bonne réponse')),
                ('difficulty', models.CharField(choices=[('EASY', 'Facile'), ('MEDIUM', 'Moyen'), ('HARD', 'Difficile')], default='MEDIUM', max_length=20, verbose_name='Difficulté de la question')),
                ('source', models.CharField(blank=True, default='', max_length=512, verbose_name='Source documentaire / Citation de référence')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='Quiz parent')),
            ],
            options={
                'verbose_name': 'Question de QCM',
                'verbose_name_plural': 'Questions de QCM',
                'db_table': 'quizzes_quizquestion',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=512, verbose_name="Texte de l'option de réponse")),
                ('is_correct', models.BooleanField(default=False, verbose_name='Est la bonne réponse')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizquestion', verbose_name='Question parente')),
            ],
            options={
                'verbose_name': 'Option de réponse',
                'verbose_name_plural': 'Options de réponse',
                'db_table': 'quizzes_quizanswer',
                'ordering': ['order'],
            },
        ),
    ]
