# Generated by Django 5.1.15 on 2026-10-07 11:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non démarré'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé')], db_index=True, default='NOT_STARTED', max_length=20, verbose_name="Statut d'apprentissage")),
                ('progress', models.FloatField(default=0.0, verbose_name='Progression globale (%)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name="Date de début d'apprentissage")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'achèvement")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='courses.course', verbose_name='Cours suivi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
            ],
            options={
                'verbose_name': "Parcours d'apprentissage",
                'verbose_name_plural': "Parcours d'apprentissage",
                'db_table': 'learning_learningpath',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='learning_le_user_id_517efd_idx'), models.Index(fields=['user', 'course'], name='learning_le_user_id_783d01_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_percent', models.FloatField(default=0.0, verbose_name='Progression de la section (%)')),
                ('last_position', models.IntegerField(default=0, verbose_name='Dernière position de lecture / défilement')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Score de maîtrise / Quiz (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progresses', to='courses.course', verbose_name='Cours')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progresses', to='courses.coursesection', verbose_name='Section / Chapitre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
            ],
            options={
                'verbose_name': 'Progression de section',
                'verbose_name_plural': 'Progressions de section',
                'db_table': 'learning_learningprogress',
                'ordering': ('section__order', 'created_at'),
                'indexes': [models.Index(fields=['user', 'course'], name='learning_le_user_id_c5ca19_idx'), models.Index(fields=['user', 'section'], name='learning_le_user_id_61e0a1_idx')],
                'unique_together': {('user', 'section')},
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Début de la session')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la session')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Durée en secondes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='courses.course', verbose_name='Cours étudié')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
            ],
            options={
                'verbose_name': "Session d'étude",
                'verbose_name_plural': "Sessions d'étude",
                'db_table': 'learning_studysession',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['user', 'course'], name='learning_st_user_id_d1948c_idx'), models.Index(fields=['user', 'started_at'], name='learning_st_user_id_f89b26_idx')],
            },
        ),
    ]
