# Generated by Django 5.1.15 on 2026-10-10 22:23

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Section déclarée terminée'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='last_viewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière consultation'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['user', 'is_completed'], name='learning_le_user_id_596338_idx'),
        ),
    ]
