# Generated by Django 5.1.15 on 2026-10-07 10:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='fr', max_length=10, verbose_name='Langue de synthèse')),
                ('voice_provider', models.CharField(default='mock', max_length=50, verbose_name='Fournisseur TTS (mock, openai, elevenlabs)')),
                ('voice_id', models.CharField(default='alloy', max_length=100, verbose_name='Identifiant de la voix')),
                ('script', models.TextField(blank=True, default='', verbose_name='Script pédagogique lu par le TTS')),
                ('storage_key', models.CharField(blank=True, default='', max_length=512, verbose_name='Clé de stockage (chemin S3 / local)')),
                ('duration', models.FloatField(default=0.0, verbose_name='Durée en secondes')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de génération'), ('COMPLETED', 'Généré'), ('FAILED', 'Échoué')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut de génération')),
                ('error_message', models.TextField(blank=True, default='', verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_contents', to='courses.course', verbose_name='Cours associé')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_contents', to='courses.coursesection', verbose_name='Section / Leçon associée')),
            ],
            options={
                'verbose_name': 'Contenu audio',
                'verbose_name_plural': 'Contenus audio',
                'db_table': 'audio_content',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['course', 'status'], name='audio_conte_course__cd31aa_idx'), models.Index(fields=['section', 'status'], name='audio_conte_section_f3448a_idx')],
            },
        ),
    ]
