# Generated by Django 5.1.15 on 2026-10-06 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_error_message_document_processing_metadata_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SUMMARY', 'Résumé'), ('KEY_POINTS', 'Points clés'), ('OBJECTIVES', 'Objectifs pédagogiques'), ('LESSON', 'Cours / Leçon'), ('REVISION_SHEET', 'Fiche de révision')], db_index=True, max_length=50, verbose_name='Type de génération')),
                ('provider', models.CharField(max_length=50, verbose_name='Fournisseur IA (openai, anthropic, gemini, local, mock)')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle LLM utilisé')),
                ('prompt_version', models.CharField(default='v1.0', max_length=20, verbose_name='Version du prompt')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name="Tokens d'entrée")),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='Tokens de sortie')),
                ('status', models.CharField(choices=[('PENDING', 'En cours'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut de la génération')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Résultat structuré')),
                ('error', models.TextField(blank=True, default='', verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='documents.document', verbose_name='Document source')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='organizations.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Génération IA',
                'verbose_name_plural': 'Générations IA',
                'db_table': 'ai_generation',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'type'], name='ai_generati_organiz_a8b680_idx'), models.Index(fields=['document', 'type'], name='ai_generati_documen_7210ea_idx'), models.Index(fields=['organization', '-created_at'], name='ai_generati_organiz_2bbad0_idx')],
            },
        ),
    ]
