# Generated by Django 5.1.15 on 2026-10-07 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la présentation')),
                ('theme', models.CharField(choices=[('modern_dark', 'Moderne Sombre'), ('minimal_light', 'Minimaliste Clair'), ('academic_indigo', 'Académique Indigo'), ('corporate_blue', 'Entreprise Bleu')], default='modern_dark', max_length=50, verbose_name='Thème graphique')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('GENERATING', 'En cours de génération'), ('READY', 'Prêt'), ('EXPORTING', 'Exportation en cours'), ('FAILED', 'Échec')], db_index=True, default='DRAFT', max_length=20, verbose_name='Statut')),
                ('storage_key', models.CharField(blank=True, default='', max_length=512, verbose_name='Clé de stockage du fichier PPTX exporté')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='courses.course', verbose_name='Cours source')),
            ],
            options={
                'verbose_name': 'Présentation',
                'verbose_name_plural': 'Présentations',
                'db_table': 'slides_presentation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PresentationSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slide_number', models.PositiveIntegerField(default=1, verbose_name="Numéro d'ordre de la slide")),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la slide')),
                ('content', models.TextField(blank=True, default='', verbose_name='Contenu didactique (puces, points clés)')),
                ('speaker_notes', models.TextField(blank=True, default='', verbose_name="Notes de l'orateur / Présentateur")),
                ('image_prompt', models.TextField(blank=True, default='', verbose_name="Prompt visuel / Idée d'illustration")),
                ('image_url', models.URLField(blank=True, default='', max_length=1024, verbose_name="URL de l'image d'illustration")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='slides.presentation', verbose_name='Présentation parente')),
            ],
            options={
                'verbose_name': 'Slide de présentation',
                'verbose_name_plural': 'Slides de présentation',
                'db_table': 'slides_presentationslide',
                'ordering': ('slide_number', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='presentation',
            index=models.Index(fields=['course', 'status'], name='slides_pres_course__8cc735_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationslide',
            index=models.Index(fields=['presentation', 'slide_number'], name='slides_pres_present_0fb688_idx'),
        ),
    ]
