# Generated by Django 5.1.15 on 2026-10-06 18:46

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_error_message_document_processing_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(help_text='Numérotation 1-indexée de la page', verbose_name='Numéro de page / slide')),
                ('text', models.TextField(blank=True, default='', verbose_name='Texte extrait')),
                ('ocr_used', models.BooleanField(default=False, help_text='Indique si le moteur OCR a été sollicité pour cette page', verbose_name='OCR utilisé')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dimensions, orientation, chapitres détectés, confiance OCR, etc.', verbose_name='Métadonnées de la page')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'extraction")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Page de document',
                'verbose_name_plural': 'Pages de documents',
                'db_table': 'ingestion_documentpage',
                'ordering': ('page_number',),
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(help_text='Ordre séquentiel du chunk dans le document', verbose_name='Index du chunk')),
                ('content', models.TextField(verbose_name='Contenu textuel du chunk')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de tokens estimés')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Préserve document, page, chapitre, section, sous-section, etc.', verbose_name='Métadonnées contextuelles')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text="Vecteur pgvector réservé pour l'indexation IA", null=True, verbose_name='Embedding vectoriel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document', verbose_name='Document')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='ingestion.documentpage', verbose_name="Page d'origine")),
            ],
            options={
                'verbose_name': 'Chunk de document',
                'verbose_name_plural': 'Chunks de documents',
                'db_table': 'ingestion_documentchunk',
                'ordering': ('chunk_index',),
            },
        ),
        migrations.AddIndex(
            model_name='documentpage',
            index=models.Index(fields=['document', 'page_number'], name='ingestion_d_documen_0f4ec3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpage',
            unique_together={('document', 'page_number')},
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='ingestion_d_documen_ddf557_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'page'], name='ingestion_d_documen_4376a7_idx'),
        ),
    ]
