# Generated by Django 5.1.15 on 2026-10-07 11:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('FREE', 'Gratuit'), ('PRO', 'Professionnel'), ('BUSINESS', 'Business'), ('ENTERPRISE', 'Entreprise')], db_index=True, default='FREE', max_length=30, verbose_name='Plan souscrit')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('TRIALING', "Période d'essai"), ('PAST_DUE', 'Paiement en attente'), ('CANCELED', 'Annulé')], db_index=True, default='ACTIVE', max_length=20, verbose_name="Statut de l'abonnement")),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Début de la période')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la période')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('billing_provider', models.CharField(default='mock', max_length=50, verbose_name='Fournisseur de facturation')),
                ('provider_customer_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID Client externe')),
                ('provider_subscription_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID Abonnement externe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization', verbose_name='Organisation abonnée')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'db_table': 'billing_subscription',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='Action réalisée')),
                ('resource_type', models.CharField(db_index=True, max_length=100, verbose_name='Type de ressource')),
                ('resource_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Identifiant ressource')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Données contextuelles')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Horodatage')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur initiateur')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'db_table': 'billing_auditlog',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'created_at'], name='billing_aud_organiz_76a6e4_idx'), models.Index(fields=['action', 'created_at'], name='billing_aud_action_a5b029_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('documents', 'Documents importés'), ('pages', 'Pages analysées'), ('storage', 'Stockage consommé (octets)'), ('ai_generations', 'Générations IA'), ('tokens', 'Jetons LLM consommés'), ('audio', 'Minutes de synthèse audio'), ('slides', 'Présentations générées'), ('quizzes', 'QCM & Examens créés')], db_index=True, max_length=50, verbose_name='Métrique suivie')),
                ('quantity', models.BigIntegerField(default=0, verbose_name='Quantité consommée')),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Début du cycle')),
                ('period_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin du cycle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Enregistrement de consommation',
                'verbose_name_plural': 'Enregistrements de consommation',
                'db_table': 'billing_usagerecord',
                'indexes': [models.Index(fields=['organization', 'metric'], name='billing_usa_organiz_daa935_idx')],
                'unique_together': {('organization', 'metric')},
            },
        ),
    ]
