# Generated by Django 5.1.15 on 2026-10-10 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('organizations', '0002_alter_organization_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('documents', 'Documents importés'), ('pages', 'Pages analysées'), ('storage', 'Stockage consommé (octets)'), ('ai_generations', 'Générations IA'), ('tokens', 'Jetons LLM consommés'), ('audio', 'Minutes de synthèse audio'), ('slides', 'Présentations générées'), ('quizzes', 'QCM & Examens créés')], db_index=True, max_length=50, verbose_name='Métrique réservée')),
                ('reserved_amount', models.BigIntegerField(default=1, verbose_name='Quantité réservée')),
                ('actual_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Quantité confirmée consommée')),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Clé d'idempotence")),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='ID de tâche Celery')),
                ('status', models.CharField(choices=[('PENDING', 'Réservé (en attente)'), ('COMMITTED', 'Consommé et confirmé'), ('RELEASED', 'Libéré / Annulé'), ('TIMEOUT_UNCERTAIN', 'Résultat fournisseur incertain')], db_index=True, default='PENDING', max_length=30, verbose_name='Statut de la réservation')),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=10, verbose_name='Coût estimé (USD)')),
                ('actual_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Coût réel confirmé (USD)')),
                ('is_cost_estimated', models.BooleanField(default=True, verbose_name='Coût estimatif (non confirmé par fournisseur)')),
                ('error_detail', models.TextField(blank=True, default='', verbose_name="Détail d'anomalie ou timeout")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Réservé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_reservations', to='organizations.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quota_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur initiateur')),
            ],
            options={
                'verbose_name': 'Réservation de quota',
                'verbose_name_plural': 'Réservations de quotas',
                'db_table': 'billing_quotareservation',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'metric', 'status'], name='billing_quo_organiz_010b5c_idx'), models.Index(fields=['organization', 'created_at'], name='billing_quo_organiz_4c4a58_idx'), models.Index(fields=['idempotency_key'], name='billing_quo_idempot_5f2287_idx')],
            },
        ),
    ]
